[package]
name = "jsonrpc-sdk-client"
version = "0.1.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]
edition = "2018"

[dependencies]
jsonrpc-sdk-prelude = { version = "=0.1.0", path = "../prelude" }
reqwest = "~0.9"
futures = "~0.1"
