[package]
name = "jsonrpc-sdk-macros"
version = "0.1.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "~0.15", features = ["full", "extra-traits"] }
quote = "~0.6"
proc-macro2 = "~0.4"
